"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import { ProductProvider } from "@/context/ProductContext";
import { AuthProvider } from "@/context/AuthContext";
import { AddProductProvider } from "@/context/AddProductContext";
import { WishlistProvider } from "@/context/WishlistContext";
import { UserProvider } from "@/context/UserContext";
import { ShippingAddressProvider } from "@/context/ShippingAddresContext";
import { CheckoutAndOrderProvider } from "@/context/CheckoutAndOrderContext";
import { ReviewsProvider } from "@/context/ReviewsContext";
import "./globals.css";

const roboto = Roboto({
  weight: ["100", "300", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <AuthProvider>
          <UserProvider>
            <AddProductProvider>
              <WishlistProvider>
                <ShippingAddressProvider>
                  <CheckoutAndOrderProvider>
                    <ReviewsProvider>
                      <ProductProvider>{children}</ProductProvider>
                    </ReviewsProvider>
                  </CheckoutAndOrderProvider>
                </ShippingAddressProvider>
              </WishlistProvider>
            </AddProductProvider>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
